language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
   - master

before_script: cd ./fatman

script:
  - make clean debug

after_success:
  - ./bin/Debug/fatman
  
notifications:
  email:
    recipients:
      - f411024@gmail.com
    on_success: change
    on_failure: always  
