language: cpp

compiler:
  - gcc

branches:
  only:
   - master

before_script: cd ./fatman

script:
  - make

notifications:
  email:
    recipients:
      - f411024@gmail.com
    on_success: change
    on_failure: always  
