language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
   - master

before_script: ls

script:
  - make && make test

notifications:
  email:
    recipients:
      - f411024@gmail.com
    on_success: change
    on_failure: always  